export const metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SELF_DOMAIN || 'http://localhost:3001'),
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
